namespace ElektroniskDodsmelding.Samples.Tests
{
    /// <summary>
    /// Contain valid JWT (JSON Web Token) from HelseId Test (https://helseid-sts.test.nhn.no/) to be used for testing.
    /// Contact <see cref="https://www.nhn.no/samhandlingsplattform/helseid">HelseID</see> to configure a client that give access to the required scopes.
    /// </summary>
    /// <remarks>
    /// Token were generated by using a sample app from HelseId.Samples (https://github.com/NorskHelsenett/HelseID.Samples)
    /// and logging in with the Test IDP with a person having the doctor role in HPR.
    ///
    /// The following scopes need to be included:
    ///    "Scope": "openid profile helseid://scopes/hpr/hpr_number helseid://scopes/identity/pid helseid://scopes/identity/security_level nhn:dodsmelding/fhir offline_access"
    /// </remarks>
    internal class TestJwt
    {
        /// <summary>
        /// Here you can fill in a valid token from a HelseId Client
        /// "helseid://claims/identity/pid": Valid FNR in Test PREG
        /// "helseid://claims/hpr/hpr_number": Valid Hpr number where the person has a valid doctor autorization/license
        /// "helseid://claims/identity/security_level": "4"
        /// </summary>
        internal const string ValidTokenWithDoctorRoleSecurityLevel4 = "[Insert jwtToken her]";
           

    }
}